local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Note that to access credentials file run rails credentials:edit. To do this on a new computer make a master.key file in config/ that has the same key as this project.
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  bucket: art-station-images
  region: us-east-1 # e.g. 'us-east-1'
  # other options to configure how it uploads
  # http_open_timeout: 0
  # http_read_timeout: 0
  # retry_limit: 0
  # upload:
  #   server_side_encryption: "" # 'aws:kms' or 'AES256'
